### ISSUE TITLE
Github button on demo site

### ISSUE THREAD

**Issue by jonathanmendes** [jjuliano/markdown-ui#2]
Really like the concept of this and excited to try it out!

Just thought you should know that the 'Github' button on the demo-page (http://jjuliano.github.io/markdown-ui/) isn't linked correctly :)

**Comment by jjuliano** [comment]
Thanks for your correction, the website itself is generated using markdown-ui so colons from urls are parsed, i'll update this later.

**Comment by jjuliano** [comment]
Fixed.
